### ISSUE TITLE
error installing rubysl-digest -v '2.0.8'

### ISSUE THREAD

**Issue by nehaboob** [rubysl/rubysl-digest#1]
gem install rubysl-digest -v '2.0.8'
Building native extensions. This could take a while...
ERROR: Error installing rubysl-digest:
ERROR: Failed to build gem native extension.

/Users/nehaboob/.rvm/rubies/ruby-2.0.0-p598/bin/ruby -r ./siteconf20160508-29924-1u51b91.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling digest.c
digest.c:544:6: error: use of undeclared identifier 'RUBY_TYPED_FREE_IMMEDIATELY'
(RUBY_TYPED_FREE_IMMEDIATELY|RUBY_TYPED_WB_PROTECTED),
^
digest.c:544:34: error: use of undeclared identifier 'RUBY_TYPED_WB_PROTECTED'
(RUBY_TYPED_FREE_IMMEDIATELY|RUBY_TYPED_WB_PROTECTED),
^
2 errors generated.
make: *** [digest.o] Error 1

**Comment by YorickPeterse** [comment]
rubysl-digest can not be used with MRI, it's meant for Rubinius instead.

**Comment by nehaboob** [comment]
thanks
